services:
  - type: worker
    name: lovetubebot
    runtime: python
    repo: https://github.com/khoja3teha/lovetubebot
    branch: main
    envVars:
      - key: BOT_TOKEN
        value: 8013306076:AAFy5_WYSfpfH7RsZcdaFti3-dcXg5z09bw
    startCommand: python main.py
